export const circulosData = [
    {
        id: 1,
        color: "bg-blue-500",
        title: "Fundación y orígenes",
        text: "Árboles jóvenes y brotes verdes que surgen de la tierra, simbolizando los inicios y la primera semilla de la empresa",
        fila: 1,
        image: "/img/nuestra-historia/74b44ddf53dcda34a08c078352370c62c2c55bdd.jpg",
        sidebarId: 1,
    },
    {
        id: 2,
        color: "bg-red-500",
        title: "Primeros logros",
        text: "Árboles jóvenes y brotes verdes que surgen de la tierra, simbolizando los inicios y la primera semilla de la empresa",
        fila: 1,
        image: "/img/nuestra-historia/1d579b8a2adf4b6b3eeaa8a5c70a9269d6f3ee42.jpg",
        sidebarId: 1,
    },
    {
        id: 3,
        color: "bg-green-500",
        title: "Apoyo institucional \n y alianzas",
        text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur enim fuga ullam sed temporibus dicta, sapiente quisquam impedit minima accusantium nobis deleniti necessitatibus recusandae eius, rerum cum. Incidunt, quibusdam. Doloribus?",
        fila: 1,
        image: "/img/nuestra-historia/3c5b06a89c5f07d246ba2b01b0f55b1f45d3e3fc.jpg",
        sidebarId: 1,
    },
    {
        id: 4,
        color: "bg-yellow-500",
        title: "Crecimiento y financiación",
        text: "Texto del círculo 4",
        fila: 2,
        image: "/img/nuestra-historia/71834ff296065182bc93b2af576503570c64de04.jpg",
        sidebarId: 1,
    },
    {
        id: 5,
        color: "bg-purple-500",
        title: "Participación en Programas de Aceleración",
        text: "Texto del círculo 5",
        fila: 2,
        image: "/img/nuestra-historia/f95b919012a07a541d7cc210be2beffc6382546e.jpg",
        sidebarId: 1,
    },
    {
        id: 6,
        color: "bg-blue-500",
        title: "Subvención del Gobierno Vasco",
        text: "Texto del círculo 6",
        fila: 1,
        image: "/img/nuestra-historia/e48a4e0dd5b5d67e66e22d7d371e41edffd8235d.jpg",
        sidebarId: 2,
    },
    {
        id: 7,
        color: "bg-red-500",
        title: "Subvención de la Diputación de Bizkaia",
        text: "Texto del círculo 7",
        fila: 1,
        image: "/img/nuestra-historia/64a7f9ef224cf7a644a7aa39eacfcb6d1420ba6c.jpg",
        sidebarId: 2,
    },
    {
        id: 8,
        color: "bg-green-500",
        title: "Primer premio en la categoría de Metaverso",
        text: "Texto del círculo 8",
        fila: 1,
        image: "/img/nuestra-historia/dc86adaba1ade38670befe65a53f5aab3d02903f.jpg",
        sidebarId: 2,
    },
    {
        id: 9,
        color: "bg-yellow-500",
        title: "Programa de subvenciones «Activa Startups»",
        text: "Texto del círculo 9",
        fila: 2,
        image: "/img/nuestra-historia/5d6936ddefc2d2e28fae54e49c7771a4c052eebf.jpg",
        sidebarId: 2,
    },
    {
        id: 10,
        color: "bg-purple-500",
        title: "Ayudas para la innovación abierta en Pymes del País Vasco",
        text: "Texto del círculo 10",
        fila: 2,
        image: "/img/nuestra-historia/cb6bda2fdb60ec17690cc4ef6fb92c304e02d66d.jpg",
        sidebarId: 2,
    },
    {
        id: 11,
        color: "bg-blue-500",
        title: "Título 11",
        text: "Texto del círculo 11",
        fila: 1,
        image: "",
        sidebarId: 3,
    },
    {
        id: 12,
        color: "bg-red-500",
        title: "Título 12",
        text: "Texto del círculo 12",
        fila: 1,
        image: "",
        sidebarId: 3,
    },
    {
        id: 13,
        color: "bg-green-500",
        title: "Título 13",
        text: "Texto del círculo 13",
        fila: 1,
        image: "",
        sidebarId: 3,
    },
    {
        id: 14,
        color: "bg-yellow-500",
        title: "Título 14",
        text: "Texto del círculo 14",
        fila: 2,
        image: "",
        sidebarId: 3,
    },
    {
        id: 15,
        color: "bg-purple-500",
        title: "Título 15",
        text: "Texto del círculo 15",
        fila: 2,
        image: "",
        sidebarId: 3,
    },
    {
        id: 16,
        color: "bg-blue-500",
        title: "Título 16",
        text: "Texto del círculo 16",
        fila: 1,
        image: "",
        sidebarId: 4,
    },
    {
        id: 17,
        color: "bg-red-500",
        title: "Título 17",
        text: "Texto del círculo 17",
        fila: 1,
        image: "",
        sidebarId: 4,
    },
    {
        id: 18,
        color: "bg-green-500",
        title: "Título 18",
        text: "Texto del círculo 18",
        fila: 1,
        image: "",
        sidebarId: 4,
    },
    {
        id: 19,
        color: "bg-yellow-500",
        title: "Título 19",
        text: "Texto del círculo 19",
        fila: 2,
        image: "",
        sidebarId: 4,
    },
    {
        id: 20,
        color: "bg-purple-500",
        title: "Título 20",
        text: "Texto del círculo 20",
        fila: 2,
        image: "",
        sidebarId: 4,
    },
];